name = "NativeCarryC3Crosswalk"
version = "0.1.0"
defaultTargets = ["NativeCarryC3Crosswalk"]

[[lean_lib]]
name = "NativeCarryC3Crosswalk"

[[require]]
name = "CPFormal"
git = "https://github.com/thiagomassensini/primos.git"
rev = "0c500e8539e7dd63b63d90b45c5c289c2830ceff"

[[require]]
name = "NativeCarrySpectralWeyl"
git = "https://github.com/thiagomassensini/native-carry-spectral-weyl.git"
rev = "ca726315be2eb9b421c07224a07967d02d07f0fb"
