name = "NativeCarryC3Crosswalk"
version = "0.3.0"
defaultTargets = ["NativeCarryC3Crosswalk"]

[[lean_lib]]
name = "NativeCarryC3Crosswalk"

[[require]]
name = "CPFormal"
git = "https://github.com/thiagomassensini/primos.git"
rev = "65d50f6db1208708e109982ba97e1d51d3039956"

[[require]]
name = "NativeCarrySpectralWeyl"
git = "https://github.com/thiagomassensini/native-carry-spectral-weyl.git"
rev = "298d83c9351e308a5213b9f5ac32e44087f98a9f"

[[require]]
name = "CarryGeometry"
git = "https://github.com/thiagomassensini/carry-geometry.git"
rev = "1f85b8c3ab5ded27a0782956e1ada0dd8a1b6fd4"
