import NativeCarryC3Crosswalk

/-!
# Kernel dependency audit

Every public theorem introduced by this package is inspected with
`#print axioms`.
-/

#print axioms NativeCarryC3Crosswalk.nativeState_eq_nativeCarryRealPlaneSample
#print axioms NativeCarryC3Crosswalk.nativeCarryRealPlaneParameter_half_eq_nativeLine
#print axioms NativeCarryC3Crosswalk.packaged_nativeState_eq_dirichletValue_nativeLine
#print axioms NativeCarryC3Crosswalk.packagedEvalStencil_eq_evalDirichletStencil
#print axioms NativeCarryC3Crosswalk.packaged_finiteNativeOperator_eq_finiteBracketCharacteristic
#print axioms NativeCarryC3Crosswalk.finiteNativeOperator_eq_zero_iff_finiteBracketCharacteristic_eq_zero
#print axioms NativeCarryC3Crosswalk.normSq_finiteBracketCharacteristic_eq_realEnergy
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficient_zero
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficient_succ
#print axioms NativeCarryC3Crosswalk.dirichletKernelHigherDeriv_zero
#print axioms NativeCarryC3Crosswalk.const_mul_ofReal_cpow_hasDerivAt
#print axioms NativeCarryC3Crosswalk.dirichletKernelHigherDeriv_succ_apply
#print axioms NativeCarryC3Crosswalk.c3BoundaryCenter_pos
#print axioms NativeCarryC3Crosswalk.package_unpackComplex
#print axioms NativeCarryC3Crosswalk.unpackComplex_package
#print axioms NativeCarryC3Crosswalk.package_c3CorrectedRealResidual
#print axioms NativeCarryC3Crosswalk.c3CorrectedCoreError_nonneg
#print axioms NativeCarryC3Crosswalk.normSq_c3CorrectedCharacteristic_eq_realEnergy
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficientExponentDeriv_zero
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficientExponentDeriv_succ
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficient_hasDerivAt
#print axioms NativeCarryC3Crosswalk.dirichletKernelHigherDeriv_hasDerivAt_exponent
#print axioms NativeCarryC3Crosswalk.c3OrientedBoundaryJet_hasDerivAt_exponent
#print axioms NativeCarryC3Crosswalk.nativeLine_hasDerivAt
#print axioms NativeCarryC3Crosswalk.c3OrientedBoundaryJet_nativeLine_hasDerivAt
#print axioms NativeCarryC3Crosswalk.c3CorrectedCharacteristic_hasDerivAt
#print axioms NativeCarryC3Crosswalk.deriv_c3CorrectedCharacteristic
#print axioms NativeCarryC3Crosswalk.package_c3CorrectedRealVelocity
#print axioms NativeCarryC3Crosswalk.c3CorrectedRealResidual_eq_unpackComplex
#print axioms NativeCarryC3Crosswalk.c3CorrectedRealResidual_hasDerivAt
#print axioms NativeCarryC3Crosswalk.deriv_c3CorrectedEnergy
#print axioms NativeCarryC3Crosswalk.isC3CorrectedStationaryCenter_iff_deriv_energy_eq_zero
#print axioms NativeCarryC3Crosswalk.c3CorrectedResidual_eq_zero_iff_realDet_eq_zero
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficientExponentSecondDeriv_zero
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficientExponentSecondDeriv_succ
#print axioms NativeCarryC3Crosswalk.dirichletSpaceCoefficientExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.dirichletKernelHigherExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.c3OrientedBoundaryJetExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.c3OrientedBoundaryJetTimeDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.dirichletValueExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.centeredBracketExponentDerivTerm_hasDerivAt
#print axioms NativeCarryC3Crosswalk.centerBracketExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.seedDirichletExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.finiteBracketCharacteristicExponentDeriv_hasDerivAt
#print axioms NativeCarryC3Crosswalk.c3CorrectedCharacteristicVelocity_hasDerivAt
#print axioms NativeCarryC3Crosswalk.deriv_c3CorrectedCharacteristicVelocity
#print axioms NativeCarryC3Crosswalk.package_c3CorrectedRealAcceleration
#print axioms NativeCarryC3Crosswalk.c3CorrectedRealVelocity_hasDerivAt
#print axioms NativeCarryC3Crosswalk.deriv_c3CorrectedStationaryNumerator
#print axioms NativeCarryC3Crosswalk.continuous_c3CorrectedStationaryNumerator
#print axioms NativeCarryC3Crosswalk.c3StationaryAnchorLower_lt_upper
#print axioms NativeCarryC3Crosswalk.c3CorrectedStationaryNumerator_strictMonoOn
#print axioms NativeCarryC3Crosswalk.existsUnique_c3CorrectedStationaryCenter
#print axioms NativeCarryC3Crosswalk.correctedStationaryCenter_mem
#print axioms NativeCarryC3Crosswalk.correctedStationaryCenter_isStationary
#print axioms NativeCarryC3Crosswalk.correctedStationaryCenter_unique
#print axioms NativeCarryC3Crosswalk.c3StationaryCoreError_nonneg
#print axioms NativeCarryC3Crosswalk.c3LedgerStationaryError_lt_endpointMargin
#print axioms NativeCarryC3Crosswalk.c3LedgerSlopeError_lt_slopeMargin
#print axioms NativeCarryC3Crosswalk.c3CorrectedStationaryNumerator_left_neg_of_ledgerEnclosures
#print axioms NativeCarryC3Crosswalk.c3CorrectedStationaryNumerator_right_pos_of_ledgerEnclosures
#print axioms NativeCarryC3Crosswalk.c3CorrectedStationarySlope_pos_of_ledgerEnclosures
#print axioms NativeCarryC3Crosswalk.C3StationaryLedgerEnclosures.toIntervalCertificate
#print axioms NativeCarryC3Crosswalk.existsUnique_c3CorrectedStationaryCenter_of_ledgerEnclosures
